all:
  children:
    web:
      hosts:
        server-one:
          ansible_host: 44.255.211.16
        server-two:
          ansible_host: 44.247.50.35
      vars:
        ansible_user: admin
        ansible_ssh_private_key_file: ~/.ssh/4640-wk7-key

